### ISSUE TITLE
CSS Hot-Module Swapping

### ISSUE THREAD

**Issue by erlandsona** [blaenk/blaenk.github.io#4]
How does Hakyll address other templating languages or DSL's like Lucid, Jade, Haml, etc... for HTML, and SASS, Less, Clay, etc... for css?

Also can Hakyll do template injection ala: https://github.com/erlandsona/Slipabeat/blob/master/app/index.html

I enjoy building nice workflows and I don't see many haskell dev's concerning themselves with some of the advancements made by the node community ala webpack, hot-module swapping, and code-splitting, until I read your post http://www.blaenkdenum.com/posts/live-editing-with-hakyll/? 

I'm hoping I can extend the system to include css and js as well?

What are your thoughts?

**Comment by blaenk** [comment]
I'm afraid the live editing I implemented is more basic than full blown webpack-style pipelines and loaders. It really just resets the article content element with the new html. And yeah you can also extend it for javascript and css if you're so inclined. Learn about Hakyll compilers and how to create your own and it should become obvious.

You can conceptually use any templating language you find packages for in haskell as long as you create a Hakyll compiler out of it.

**Comment by erlandsona** [comment]
Nice! I'll be looking into that more after I get the project built from the commit you mentioned in your email! Thanks again!
